version: '3.9'
volumes:
  db:
    driver: local
networks:
  hobbitlink:
    driver: bridge
services:
  ui:
    container_name: ui
    build: './ui'
    networks:
      - hobbitlink
    volumes:
      - ./ui/:/app
    working_dir: /app
    ports:
      - '${UI_PORT}:${UI_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - UI_PORT=${UI_PORT}
  api:
    container_name: api
    build: './api'
    networks:
      - hobbitlink
    volumes:
      - ./api/:/app
    working_dir: /app
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - APP_NAME=${APP_NAME}
      - APP_VER=${APP_VER}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  db:
    container_name: db
    build: './db'
    networks:
      - hobbitlink
    volumes: 
      - db:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
