version: '3.9'
volumes:
  db:
    driver: local
networks:
  hobbitlink:
    driver: bridge
services:
  server:
    container_name: server
    image: node:16.13.0-alpine3.14@sha256:3bca55259ada636e5fee8f2836aba7fa01fed7afd0652e12773ad44af95868b9
    command: npm run start:dev
    working_dir: /server
    networks:
      - hobbitlink
    volumes:
      - ./:/server
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      NODE_PORT: 8080
      APP_NAME: hobbitlink
      APP_VER: 1.0.0
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: hobbitlink
      MYSQL_PASSWORD: pj9FCeYSgQ6BJdrMsxKR3p
      MYSQL_DATABASE: hobbitlink
  database:
    container_name: database
    image: mysql:8.0@sha256:eb791004631abe3bf842b3597043318d19a91e8c86adca55a5f6d4d7b409f2ac
    networks:
      - hobbitlink
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes: 
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hobbitlink
      MYSQL_USER: hobbitlink
      MYSQL_PASSWORD: pj9FCeYSgQ6BJdrMsxKR3p
      MYSQL_ROOT_PASSWORD: HAam33kF6PKB8eFmdmCTHD
