name: api-workflow
on:
  push:
    paths:
      - 'api/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build app
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - run: npm ci
      - run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test app
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - run: npm test
