name: ui-workflow
on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ui*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './ui'
    steps:
      - uses: actions/checkout@v3
      - name: Select
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Lint
        run: npm run lint
